### ISSUE TITLE
Enhancements That I Would Love To See

### ISSUE THREAD

**Issue by slamijami** [ocapraro/obsidian-math-plus#13]
Hey! I love this plugin for letting me sketch and handwrite directly in notes, it's that last 'piece' obsidian is missing.
Currently stopping this from being an S-tier plug-in are:
 - The lack of an eraser 
 - The pen size is way too phat
 - The UI is a bit chunky and ugly

Cheers!

**Comment by ocapraro** [comment]
Thanks for the feedback! The UI definitely needs some reworking, which I'm planning on doing in the near future. Unfortunately, I don't have much control over the pen size since it is an excalidraw feature, but I will try my best to add as much variability as possible. There is an eraser in excalidraw, so I will add it as an option to enable it in the settings. If you have any specific recommendations for fixing the UI, I'd love to hear them. Thanks!
