### ISSUE TITLE
Resize handle unselectable when using Minimal theme

### ISSUE THREAD

**Issue by j-maffe** [ocapraro/obsidian-math-plus#16]
Hello! I really love this plugin :D. For some reason tho, the Minimal theme is preventing dragging the resize handle. Instead of the up and down arrows, I just see the regular text cursor. I'm not sure if there's any setting in Minimal to fix this. Thought I'd let you know

**Comment by ocapraro** [comment]
It seems to work for me, so I'm marking this issue as resolved since it took me a while to get to this. If it's still not working for you could you send me a recording of the problem, and the css file for your theme just incase we're using different versions. Thanks!

https://github.com/ocapraro/obsidian-math-plus/assets/25327166/280f28d5-c09d-40cd-9f13-9149644885d9
