### ISSUE TITLE
Can't create different math blocks!

### ISSUE THREAD

**Issue by noiseandsmke** [ocapraro/obsidian-math-plus#19]
Hi there, I have a problem that when I create a new math block file it become **data-undefined** in both folders **drawings** and **excalidraw-files**. So that, I cant have more than 2 different math blocks. It wasn't create a new one for me, just the same display as first block created before. Please help me to fix it. A month ago, I still use it normally!!! Thanks for your helping

![image](https://github.com/ocapraro/obsidian-math-plus/assets/121669389/1fe7c4be-752b-4e52-898d-3f62bec1f723)

**Comment by ocapraro** [comment]
Could you include a plain text version of the document this is happening in? I'm not positive, but it looks like your math blocks are sharing the same ID which could occur if the math blocks were copied and pasted instead of creating a new one using the command, but I can't be sure without seeing the metadata included in them.
