### ISSUE TITLE
[Bug] \sum always renders with an m subscript?

### ISSUE THREAD

**Issue by afland** [ocapraro/obsidian-math-plus#4]
![image](https://user-images.githubusercontent.com/67392684/184227939-33f9b562-e015-4bc3-9619-307cf86ee964.png)

renders as 

![image](https://user-images.githubusercontent.com/67392684/184228013-d7d4f4f9-db47-4631-a0a8-8ab5f36528c3.png)

I don't know why that m is there, but I can't write sums correctly because of that. 

Another thing: 

![image](https://user-images.githubusercontent.com/67392684/184228511-179b1708-eb17-4dbd-899a-df83ee32bf5b.png)
 
my excalidraw menu always renders horizontally, but I see it's vertical in the README screenshot. Is there a way to configure it like that?

**Comment by ocapraro** [comment]
Hi @afland, sorry it took me so long to get around to this. The m subscript is a result of the \su shortcut that I was using to write sums, I've now made shortcuts configurable from settings, and removed that one from the default batch. If you have any more problems where things are rendering weird, it is most likely a shortcut problem where it's overwriting a standard latex command. You can now fix problems like that using the shortcuts settings option.

Your menu is rendering horizontally because the math block you are in is too short for it to render vertically. You can change the size of your math block by dragging the bottom right corner. If that still doesn't work, let me know along with some details of your device+obsidian version. I

 hope this helps, thanks for providing feedback!
