### ISSUE TITLE
Excalidraw drawings overwrite each other on same note

### ISSUE THREAD

**Issue by projotce** [ocapraro/obsidian-math-plus#7]
Each new drawing I do overwrites the other ones within the same notes when I close and open Obsidian. There's also an issue where the Excalidraw instance blocks out the typed math, though I was able to resolve that for now by uninstalling and reinstalling the plugin. 

![image](https://user-images.githubusercontent.com/19521732/206263229-e169744d-37ac-45fa-be67-f0058bf46f0b.png)

**Comment by ocapraro** [comment]
Sorry it took so long to get back to you, could you include a plain text version of the document this is happening in? I'm not positive, but it looks like your math blocks are sharing the same ID which could occur if the math blocks were copied and pasted instead of creating a new one using the command, but I can't be sure without seeing the metadata included in them.

**Comment by ocapraro** [comment]
Stale
